services:
  #--- DATABASES
  ppm-user-psql:
    image: postgres:latest
    container_name: ppm-user-psql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: users
    volumes:
      - ppm-postgres-data:/var/lib/postgresql/data

volumes:
  ppm-postgres-data:
    driver: local