eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST}:${DISCOVERY_PORT}/eureka
spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: postgres
    password: postgres
  threads:
    virtual:
      enabled: true
  application:
    name: UserService
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8081